name: Electron Build

on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build Electron application (Windows)
        if: ${{ matrix.platform == 'windows-latest' }}
        run: npm run build -- --win

      - name: Build Electron application (macOS)
        if: ${{ matrix.platform == 'macos-latest' }}
        run: npm run build -- --mac

      - name: Build Electron application (Linux)
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: npm run build -- --linux

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: electron-app-${{ matrix.platform }}
          path: dist
